### ISSUE TITLE
error on load

### ISSUE THREAD

**Issue by Logikoz** [et-nik/fastdl-mm#1]
```
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from ptero-eggs/games 
Digest: sha256:af90d73085cb2ec25912509e1b094ff6558c3ab07a3a372e6b5c223ca844e90c 
Status: Image is up to date for ghcr.io/ptero-eggs/games:source 
[Pterodactyl Daemon]: Finished pulling Docker container image
steam user is not set.
Using anonymous user.
Not updating game server as auto update was set to 0. Starting Server
:/home/container$ ./hlds_run -console -game ${HLDS_GAME} -port ${SERVER_PORT} -sport ${VAC_PORT} +map ${SRCDS_MAP} +ip 0.0.0.0 -strictportbind -norestart +maxplayers 32 +pingboost 2 +sys_ticrate 1200
Console initialized.
Using breakpad crash handler
Setting breakpad minidump AppID = 10
Forcing breakpad minidump interfaces to load
Looking up breakpad interfaces from steamclient
Calling BreakpadMiniDumpSystemInit
Protocol version 48
Exe version 1.1.2.7/Stdio (cstrike)
Exe build: 14:03:01 Jul 25 2021 (2661)
STEAM Auth Server
Server IP address 0.0.0.0:27083
   
   Metamod-r version 1.3.0.149 Copyright (c) 2016-2018 ReHLDS Team (rebuild of original Metamod by Will Day and Jussi Kivilinna)
   Metamod-r comes with ABSOLUTELY NO WARRANTY; for details type `meta gpl'.
   This is free software, and you are welcome to redistribute it
   under certain conditions; type `meta gpl' for details.
   
Metamod-r v1.3.0.149, API (5:13)
Metamod-r build: 11:31:21 Apr 23 2024
Metamod-r from: https://github.com/theAsmodai/metamod-r/commit/603a257
   AMX Mod X version 1.10.0.5467 Copyright (c) 2004-2015 AMX Mod X Development Team 
   AMX Mod X comes with ABSOLUTELY NO WARRANTY; for details type `amxx gpl'.
   This is free software and you are welcome to redistribute it under 
   certain conditions; type 'amxx gpl' for details.
  
L 03/10/2025 - 03:57:33: [GEOIP] Database info: GeoLite2 Country database 2.0
panic: host is not set, please set host or customDownloadURL in config
goroutine 17 [running, locked to thread]:
main.init.0.metaQueryFn.func7()
        /home/runner/work/fastdl-mm/fastdl-mm/main.go:168 +0x6a2
github.com/et-nik/metamod-go.Meta_Query(0xecaf0aac, 0xa7ca048, 0xa7ca08c)
        /home/runner/go/pkg/mod/github.com/et-nik/metamod-go@v0.3.3/meta_api.go:46 +0x101
/entrypoint.sh: line 73:    15 Aborted                 (core dumped) ./hlds_run -console -game ${HLDS_GAME} -port ${SERVER_PORT} -sport ${VAC_PORT} +map ${SRCDS_MAP} +ip 0.0.0.0 -strictportbind -norestart +maxplayers 32 +pingboost 2 +sys_ticrate 1200
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 134
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.
```

version: 0.5.0

my config:
```
# fastdl.yaml

# The host of the FastDL HTTP server. 
# Leave it empty if you want to use the same IP as the game server.
# host: "127.0.0.1"

# The port of the FastDL HTTP server. 
# Leave it empty if you want to use random port.
# port: 13080

# The range of random ports for the FastDL HTTP server.
# If the port is not specified, the plugin will use a random port from this range.
# If the port is specified, the plugin will use the specified port, ignoring this range.
#portRange: 40000-50000

# Serve only precached files. 
# If enabled, the plugin will not allow downloading files that are not in the precache list.
servePrecached: false

# Generate auto index page for directories. 
# It allows to see the list of files in the directory.
autoIndexEnabled: true

# Cache size for downloaded files. 
# The plugin will delete the oldest files if the cache is full.
cacheSize: 300MB

# Forbidden files and directories by regular expressions.
forbiddenRegexp:
  - mapcycle.*
  - .*textscheme.*
    
# Allowed file extensions. 
# Files with extensions not in this list can not be downloaded.
allowedExtensions:
  - bmp
  - bsp
  - gif
  - jpeg
  - jpg
  - lmp
  - lst
  - mdl
  - mp3
  - png
  - res
  - spr
  - tga
  - txt
  - wad
  - wav
  - zip

# Allowed paths. 
# Files from directories not in this list can not be downloaded.
allowedPaths:
  - gfx
  - maps
  - media
  - models
  - overviews
  - sound
  - sprites

# Block IP addresses by single IP, IP subnet or IP range.
# It supports IPv4 and IPv6.
#blockListIP:
#  - 192.0.2.1
#  - 10.80.0.0/24
#  - 172.12.132.1-172.12.132.20

# Rate limiting for IP addresses.
rateLimits:

  - limit: 5
    period: 1s
    
  - limit: 100
    period: 1m
```
